# basic config
baseurl: https://blog.chenxi-eumenides.top
title: chenxiçš„ä¸ªäººåšå®¢

enableEmoji: true
enableGitInfo: true
googleAnalytics:

ignoreErrors:
  - "error-remote-getjson"

# theme
theme: hugo-theme-stack
disqusShortname: hugo-theme-stack

# language
DefaultContentLanguage: zh-cn
languageCode: zh-cn
hasCJKLanguage: true
languages:
  zh-cn:
    languageName: ä¸­æ–‡
    title: chenxiçš„ä¸ªäººåšå®¢
    description: chenxi
    weight: 1

# custom config
paginate: 10
permalinks:
  post: /p/:slug/
  page: /:slug/
params:
  mainSections:
    - post
    #- about
  featuredImageField: image
  rssFullContent: true
  favicon: /web_icon.ico

  colorScheme:
    toggle: true
    default: auto

  footer:
    since: 2023
    customText: è®°å½•æˆ‘æ‰€ç»å†çš„ã€‚

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: ğŸŒ
    subtitle: æˆ‘æ€»åœ¨çœ‹è¿™ä¸ªä¸–ç•Œã€‚ç¾å¥½é‚£ä¹ˆå¤šï¼Œå›å¿†é‚£ä¹ˆè¿œã€‚
    avatar:
      enabled: true
      local: true
      src: img/avatar-3.jpg

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10

    page:
      - type: search
      - type: toc
      - type: categories
        params:
          limit: 10

  comments:
    enabled: false
    provider: disqus

  opengraph:
    twitter:
      site: cx_Eumenides

      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/chenxi-Eumenides
      params:
        icon: svg/brand-github

    - identifier: qq
      name: QQ
      url: tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=174241477
      params:
        icon: svg/brand-qq

    - identifier: bilibili
      name: Bilibili
      url: https://space.bilibili.com/34515347
      params:
        icon: svg/brand-bilibili

    - identifier: steam
      name: Steam
      url: https://space.bilibili.com/34515347
      params:
        icon: svg/brand-steam

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4

frontmatter:
  lastmod: [":fileModTime", ":git", "lastmod", ":default"]
